# Generated by Django 3.2.4 on 2021-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0003_auto_20210626_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='ignore',
            field=models.BooleanField(default=True),
        ),
    ]
