# Generated by Django 3.2.4 on 2021-06-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0004_alert_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
