# Generated by Django 3.2.4 on 2021-06-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0006_auto_20210628_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='country_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
