# Generated by Django 3.2.4 on 2021-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0007_alter_expert_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='country',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
