# Generated by Django 3.2.7 on 2021-11-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0008_auto_20210628_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='gdacs_accesslevel',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_acknowledgements',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_alertlevel',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_alertscore',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_bbox',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_calculationtype',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_cap',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_country',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_description',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_durationinweek',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_episodealertlevel',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_episodealertscore',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_episodeid',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_eventid',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_eventname',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_eventtype',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_fromdate',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_glide',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_gtsimage',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_gtslink',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_icon',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_iscurrent',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_iso3',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_mapimage',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_maplink',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_population',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_resource',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_resources',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_severity',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_temporary',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_title',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_todate',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_version',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_vulnerability',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='gdacs_year',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='geo_long',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='geo_point',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='guidislink',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='link',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='links',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='published',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='published_parsed',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='summary',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='summary_detail',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='tags',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='title',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='title_detail',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='alert',
            name='uid',
            field=models.CharField(blank=True, max_length=2500),
        ),
    ]
