# Generated by Django 3.2.7 on 2021-11-12 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0009_auto_20211112_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='content',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='daterecieved',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='ignore',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='uuid',
        ),
    ]
