# Generated by Django 3.2.8 on 2021-11-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0010_auto_20211112_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='gdacs_fromdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='gdacs_todate',
            field=models.DateTimeField(),
        ),
    ]
