# Generated by Django 3.2.4 on 2021-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdn', '0002_auto_20210625_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='alert',
            name='source_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
